### ISSUE TITLE
[UI] Search button overlaps search bar

### ISSUE THREAD

**Issue by Erikmitk** [slub/slub_digitalcollections#2]
The search icon overlaps the search bar's rounded corners.

![image](https://user-images.githubusercontent.com/180686/78653913-176a7f80-78c4-11ea-8675-bc27ec0de307.jpeg)

Reported via: https://twitter.com/nilswindisch/status/1247411970858463232/photo/1

**Comment by albig** [comment]
Issue still persist **_on focus_** the input field in Workview -> SearchInDocument.

E.g. [http://digital.slub-dresden.de/id166356356X](https://digital.slub-dresden.de/werkansicht/dlf/332867/52/?tx_dlf%5Bhighlight_word%5D=dresden)

![Screenshot-SearchInDocument](https://user-images.githubusercontent.com/3354500/98788998-ede97780-2401-11eb-9a9c-af55c619a07a.png)

**Comment by albig** [comment]
Fixed by #11
