### ISSUE TITLE
Search for newspaper title and newspaper does not work

### ISSUE THREAD

**Issue by andre-hohmann** [slub/slub_digitalcollections#3]
The Search in newspaper titles and newspaper years does not work, because the METS-files do not contain fulltext. Several users asked for the search, because it worked formerly. 

Thus the demand is:
Enhancement of the search, that the search is conducted in the METS-files of all issues belonging to the title, respectively the year. 

Examples: 
- http://digital.slub-dresden.de/id512384843-1896
- http://digital.slub-dresden.de/id501434038-1909

**Comment by albig** [comment]
This should be fixed in #17 together with https://github.com/kitodo/kitodo-presentation/pull/545
