### ISSUE TITLE
[BUG] Call to undefined method `getDoc()`

### ISSUE THREAD

**Issue by csidirop** [slub/slub_digitalcollections#56]
Using the newest code in .presentation and dfg-viewer following exception is thrown when opening a document:

`Call to undefined method Kitodo\Dlf\Domain\Model\Document::getDoc() | Error thrown in file /var/www/typo3/public/typo3conf/ext/slub_digitalcollections/Classes/ViewHelpers/XpathViewHelper.php in line 105.`

See https://github.com/kitodo/kitodo-presentation/issues/1029 and https://github.com/kitodo/kitodo-presentation/pull/885

**Comment by beatrycze-volk** [comment]
This issue is already adressed in https://github.com/slub/slub_digitalcollections/pull/55/files

**Comment by csidirop** [comment]
Oh, my fault sorry!

**Comment by csidirop** [comment]
Fixed as #55 got merged
