### ISSUE TITLE
Installing via packagist.org gets us only presentation v4.1

### ISSUE THREAD

**Issue by csidirop** [slub/slub_digitalcollections#86]
As the restrain to allow [presentation versions till v5.x came in May](https://github.com/slub/slub_digitalcollections/commit/a52354604e8cf1b44646092739413722feab0843) after the the current [v3.1.0 release](https://github.com/slub/slub_digitalcollections/releases/tag/v3.1.0) from April this year, other packages requiring the slub_digitalcollections together with the newest presentation version (as [your DFG-Viewer](https://github.com/slub/dfg-viewer/blob/cd505b05ec7a865fcd9868998509e19f03252043/composer.json#L46)) cannot be installed via composer:

```
Problem 1
  - Root composer.json requires slub/dfgviewer ^6.1 -> satisfiable by slub/dfgviewer[v6.1.0].
  - slub/dfgviewer v6.1.0 requires slub/slub-digitalcollections ^3.0|dev-master -> satisfiable by slub/slub-digitalcollections[v3.0.0, v3.0.1, v3.1.0].
  - slub/slub-digitalcollections v3.1.0 requires kitodo/presentation ^4.1|dev-master -> satisfiable by kitodo/presentation[v4.1.0].
  - slub/slub-digitalcollections[v3.0.0, ..., v3.0.1] require kitodo/presentation ^4.0|dev-master -> satisfiable by kitodo/presentation[v4.0.0, v4.0.1, v4.1.0].
  - You can only install one version of a package, so only one of these can be installed: kitodo/presentation[v4.0.0, v4.0.1, v4.1.0, v5.0.0, v5.0.1].
  - slub/dfgviewer v6.1.0 requires kitodo/presentation ^5.0|dev-master -> satisfiable by kitodo/presentation[v5.0.0, v5.0.1].
  - Conclusion: don't install kitodo/presentation v5.0.1 (conflict analysis result)
```

I would suggest to release a new minor version (like 3.2.0) or a major version if you think that fits better.

As reference the packagist.org repo: https://packagist.org/packages/slub/slub-digitalcollections#v3.1.0

**Comment by csidirop** [comment]
push

**Comment by beatrycze-volk** [comment]
The versions were updated. It should be possible to install the DFG Viewer without version conflicts.

@csidirop can you confirm it?

**Comment by csidirop** [comment]
Looks good! Thank you
