### ISSUE TITLE
List of structure elements cannot be scrolled in the mobile view

### ISSUE THREAD

**Issue by andre-hohmann** [slub/slub_digitalcollections#9]
### Problem
In "Digitale Sammlungen" und "Börsenblatt-Digital" [(slub_digitalcollections)](https://github.com/slub/slub_digitalcollections) it is not possible to scroll the list of structure elements in the mobile view and in small browser windows. 

See also #10

### Solution
It should be possible to scroll in the list of structure elements

### Examples
- http://digital.slub-dresden.de/id365171654
- http://digital.slub-dresden.de/id416501729

![strukturbaum](https://user-images.githubusercontent.com/14835770/98775465-7e698d00-23ed-11eb-936d-0c2f7800d1b6.jpg)

**Comment by albig** [comment]
@gnuj please have a look at it.
